// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
 require('dotenv').config();
 const docType = process.env.REACT_APP_DOC_TYPE;

 const sidebars = {
  docSidebar: [
    {
      type: 'autogenerated',
      dirName: docType, // Points to docs/retailer or docs/supplier
    },
  ],
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: `api/${docType}`, // Points to docs/retailer or docs/supplier
    },
  ],
};

console.log(35, "====================", sidebars)

export default sidebars;
